name: enerren
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.53

environment:
  sdk: ">=2.17.6 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  dio: ^4.0.4
  permission_handler: ^8.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.18
  flutter_launcher_icons: ^0.9.0
  shared_preferences: ^2.0.12
  intl: ^0.18.0
  geolocator: 7.0.0
  geocoding: ^2.1.0
  flutter_svg: ^2.0.7
  device_info_plus: ^4.0.0
  move_to_background: ^1.0.2
  sprintf: ^6.0.0
  random_string: ^2.3.1
  local_post_management:
    git:
      url: https://github.com/nandanghermawan21/local_post_management.git
      ref: master
  circular_loader:
    git:
      url: https://github.com/nandanghermawan21/circular_loader.git
      ref: main
  list_data:
    git:
      url: https://github.com/nandanghermawan21/list_data.git
      ref: master
  my_image_picker:
    git:
      url: https://github.com/nandanghermawan21/my_image_picker.git
      ref: master
  db_migration:
    git:
      url: https://github.com/nandanghermawan21/db_migration.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.0 
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - dbmigration/
    - dbquery/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
